[colors.bright]
black = "#777777"
blue = "#6f8fdb"
cyan = "#4ac9e2"
green = "#88db3f"
magenta = "#e987e9"
red = "#f36868"
white = "#f0f0f0"
yellow = "#f0bf7a"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#2e404f"
blue = "#4a88e4"
cyan = "#23acdd"
green = "#73ca50"
magenta = "#915caf"
red = "#e15d56"
white = "#ffffff"
yellow = "#e9bf57"

[colors.primary]
background = "#17152b"
foreground = "#f9f8fe"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.normal]
family = "JetBrainsMono"
style = "Bold"

[scrolling]
history = 1000

[window]
opacity = 0.9
dynamic_padding = true
[window.padding]
x = 4
y = 4
