#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#2e3440"

sxhkd &
polybar &
setxkbmap -model pc104 -layout us,ru -option grp:alt_shift_toggle &
xwinwrap -ni -b -fs -nf -ov -debug -g 1920x1080 -- gifview -w WID -a $HOME/Pictures/2641074.gif &
#feh --bg-scale ~/Pictures/wallpapper.jpg
picom --config ~/.config/picom/picom.conf
